### ISSUE TITLE
Support for Light and Dark Splash Screen

### ISSUE THREAD

**Issue by hectorAguero** [henriquearthur/flutter_native_splash#17]
So In android is very easy to implement a Dark Splash Screen for devices with Android 9 or 10, because the sistem recognize a values-night folder inside the res folder.

 In the image below I don't use the `launch_background_night.xml` and `splash_night.png` files, because my image looks fine in light and dark background, so in this case the `values-night/styles.xml`and `values/styles.xml` call the same file in `android:windowBackground`.

But if had a dark logo and light logo, I need to call to `launch_background.xml` and `launch_background_night.xml` respectively and these need to call to `splash.png` and `splash-night.png` respectively.

I don't know much about this process on ios, but I know that you need Xcode 10(or 10.2) to set a Dark and Light Splash Screen.

![image](https://i.imgur.com/wB6ap9E.png)

**Comment by henriquearthur** [comment]
This would be a great feature indeed, specially with dark mode being supported everywhere nowadays.

Will look into this soon. PRs are welcome.

Thanks!

**Comment by IoanaAlexandru** [comment]
Any updates on this? It would be really useful...

**Comment by tapizquent** [comment]
Has there been any progress with this? This feature would be amazing indeed

**Comment by MaheshPeri19** [comment]
How to make **dark theme as default theme** in my app ? 

If i place like below in pubspec.yaml file, it is taking light theme as default theme. I want to **make dark theme as default** and i can change later in app settings. 

Any suggesstions ?

```
flutter_native_splash:
  color: "#EAEAEA"
  image: "assets/images/splash_screen/logo473.png"

  color_dark: "#000000"
  image_dark: "assets/images/splash_screen/logo.png"
  android: true
  ios: true
```
