### ISSUE TITLE
Fails with new Flutter embedding system for v2 Android Embedding

### ISSUE THREAD

**Issue by MikeMannox** [henriquearthur/flutter_native_splash#35]
With the latest update to Flutter (I am on `1.13.2`) a new v2 of the Android embedding API was introduced. 

Running:
```cli
flutter create --template app --description "Fluttering" --ios-language "swift" --android-language "kotlin" --org "xyz.flutter" app
```
Generates new an Android project with some subtle differences:

`AndroidManiest.xml` with
```xml
     <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```

`MainActivity.kt` with no `onCreate` and a new method:
```kotlin
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
```

Adding 
```yaml
dev_dependencies:
  flutter_native_splash: 0.1.9

flutter_native_splash:
  image: assets/splash.png
  color: ffcc11
  fill: true
```
and then executing:
```cli
flutter pub pub run flutter_native_splash:create
```
updates the `drawables/*` and `colors.xml`, but fails to with `MainActivity.kt` 
Sometimes you see the splash for a flicker of a second, followed by a black screen before the Flutter content shows
