### ISSUE TITLE
AlertDialog hidden by keyboard after adding flutter_native_splash: ^0.1.9

### ISSUE THREAD

**Issue by zgramming** [henriquearthur/flutter_native_splash#39]
I know this issue so strange but it's happen to me, I don't know why after adding this package if i showing Alert Dialog , My dialog hidden by keyboard .
After running this command `flutter pub pub run flutter_native_splash:create` and running the app.
## Using Flutter native splash Packages
![alertdialog hidden by keyboard because using flutter native splash package](https://user-images.githubusercontent.com/38829404/71398678-c657b800-2653-11ea-927e-bfd0e02559e9.jpeg)

## Source Code 
```
import 'package:flutter/material.dart';

void main() {
  // WidgetsFlutterBinding.ensureInitialized();
  return runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: "Mateiral App", home: TestingPage());
  }
}

class TestingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlatButton(
          color: Colors.red,
          onPressed: () => showDialog(
            context: context,
            builder: (ctxDialog) => SimpleDialog(),
          ),
          child: Text('Show Dialog'),
        ),
      ),
    );
  }
}

class SimpleDialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('Testing DIALOG'),
      content: TextFormField(
        decoration: InputDecoration(
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(30)),
        ),
      ),
      actions: <Widget>[
        FlatButton.icon(
            onPressed: () => "", icon: Icon(Icons.add), label: Text('ttest')),
        FlatButton.icon(
            onPressed: () => "", icon: Icon(Icons.add), label: Text('ttest')),
      ],
    );
  }
}

```

### Pubspec.yaml
```
name: flutter_native_splash_bug
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4

flutter_native_splash:
  image: assets/1.png
  color: "42a5f5"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/1.png"
flutter:
  uses-material-design: true

```

## Without Flutter Native Splash 
![alertdialog without flutter native splash](https://user-images.githubusercontent.com/38829404/71398881-7c230680-2654-11ea-9215-c154e292f07c.jpeg)

### Source Code
```
import 'package:flutter/material.dart';

void main() {
  // WidgetsFlutterBinding.ensureInitialized();
  return runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: "Mateiral App", home: TestingPage());
  }
}

class TestingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FlatButton(
          color: Colors.red,
          onPressed: () => showDialog(
            context: context,
            builder: (ctxDialog) => SimpleDialog(),
          ),
          child: Text('Show Dialog'),
        ),
      ),
    );
  }
}

class SimpleDialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text('Testing DIALOG'),
      content: TextFormField(
        decoration: InputDecoration(
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(30)),
        ),
      ),
      actions: <Widget>[
        FlatButton.icon(
            onPressed: () => "", icon: Icon(Icons.add), label: Text('ttest')),
        FlatButton.icon(
            onPressed: () => "", icon: Icon(Icons.add), label: Text('ttest')),
      ],
    );
  }
}

```
## Pubspec.yaml
```
name: without_flutter_native_splash
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/1.png"
flutter:
  uses-material-design: true

```
