### ISSUE TITLE
The status bar will be hidden when you set android_disable_fullscreen to true, except for the splash screen.

### ISSUE THREAD

**Issue by basashi-G** [henriquearthur/flutter_native_splash#72]

**Comment by basashi-G** [comment]
The status bar will be hidden when you set android_disable_fullscreen to true, except for the splash screen, Like this.

![Screenshot_1591255189](https://user-images.githubusercontent.com/53048311/83726936-3c3e6180-a67f-11ea-8268-93a4a6a597b6.png)

**Comment by ninest** [comment]
I was also experiencing the same problem. I believe you have to write some Java/Kotlin code to fix. In the mean time, I fixed it disabling fullscreen:
```yaml
flutter_native_splash:
  image: "icons/splash.png"
  color: "111111"
  android_disable_fullscreen: true
```

Similar issue: #67
